### ISSUE TITLE
On French Windows 10 bb is in English

### ISSUE THREAD

**Issue by LAfricain** [postiffm/bibledit-desktop#50] opened 2018-04-22 14:01 UTC
After installing BB on windows it was not displaying to French only to English.
Another remark, maybe it should be named Bibledit-Desktop and not Bibledit because bibledit is currently the Teus one...

**Comment by postiffm** [comment] 2018-04-22 20:59
Make sure you are using the following command line in your shortcut that starts Bibledit-Desktop. "C:\Program Files\Bibledit-4.12\editor\bin\bibledit-fr.cmd" --debug  

I just committed an improved version of the .cmd file to the repo. Try putting that in C:\Program Files\Bibledit-4.12 (or whatever directory)...

Please send additional information if you are able. I can confirm that the same bug happens on my end. Not sure what changed to cause this error.

**Comment by postiffm** [comment] 2018-04-23 13:18
In "French" mode on my computer, there appears to be a problem with this build variable from config.h.

BIBLEDIT_LOCALEDIR /mingw64/share/locale

Some others are not quite right either:

T1 LANGUAGE      	fr
T1 LANG          	LANG variable not specified
T1 LC_ALL        	English_United States.1252
T1 LC_CTYPE      	English_United States.1252

**Comment by postiffm** [comment] 2018-04-23 15:14
The problem is that the bibledit-desktop.mo file was not in the right spot. It needs to be in C:\Program Files\Bibledit-4.14\editor\share\locale\fr\LC_MESSAGES\bibledit-desktop.mo.

The file was there, but incorrectly named as just bibledit.mo. I'm not sure how this came about. Version 4.14 (to be released soon) will fix this problem.

**Comment by postiffm** [comment] 2018-04-23 23:40
In debugging this, I found something else strange. Debug output shows the following on windows:

BIBLEDIT_LOCALEDIR /mingw64/share/locale

This is incorrect--Windows can't interpret this path. it is defined on the build command line like this:

 -DBIBLEDIT_LOCALEDIR=\"/mingw64/share/locale\"

and also it is defined in bibledit-desktop/config.h like this:

#define BIBLEDIT_LOCALEDIR "/mingw64/share/locale"

It should be

#define BIBLEDIT_LOCALEDIR "C:\\Program Files\\Bibledit-4.14\\editor\\share\\locale"

I would think that the right way to fix this is to build it like this:

./configure --prefix "C:/Program Files/Bibledit-4.14/editor"

Unfortunately, this results in g++ erroring out with a message like "Files/Bibledit-4.14/editor/share/locale/ not found." It doesn't like the space in the path name, and perhaps this needs to be double-escaped in the Makefile for it to work. I'm not sure.

Anyone have ideas?

**Comment by postiffm** [comment] 2018-04-26 11:51
This is verified as fixed.

**Closed by postiffm** 2018-04-26 11:51 UTC
