### ISSUE TITLE
Backup option where is the backup?

### ISSUE THREAD

**Issue by LAfricain** [postiffm/bibledit-desktop#18] opened 2017-05-11 11:49 UTC
Hi,
I tried the backup option. At the end of the process it say that everything runs well but I can't see the backup? Where is it?
![backup_bb](https://cloud.githubusercontent.com/assets/19690477/25945904/ac0a0440-3640-11e7-84e4-a92ac295867a.png)

**Comment by postiffm** [comment] 2017-05-13 16:07
Hi, look in c:\users\username\.bibledit for the backup, which has a name that reflects the date and time that the backup was made.

Admittedly, there is some kind of bug in this simplified backup code that doesn't work as intended. But at least the backup is created. Let me know if you cannot find it.

**Comment by LAfricain** [comment] 2017-05-13 18:58
I use Ubuntu. I found it in $HOME/.bibledit/projects/project_name

**Comment by postiffm** [comment] 2017-05-13 20:41
OK, perhaps you only backed up the project instead of "everything"

**Comment by LAfricain** [comment] 2017-05-14 06:59
I don't undestand what you want to say.

**Comment by postiffm** [comment] 2017-05-16 18:35
I have made an important bug-fix in the Backup-Everything option. Fixed in bcc9af4da09dec26024e7c80554575947567d54f

**Closed** 2017-05-16 18:38 UTC

**Comment by LAfricain** [comment] 2017-05-16 18:40
Thanks !
